### PR TITLE
My Talk "Off the Tracks - Challenging the Rails Mindset"

### PR DESCRIPTION
**Pull request by apotonick**

### CODE REVIEW

**Comment by ursm** [comment]
:+1:

**Comment by kenchan** [comment]
+1

**Comment by kakutani** [comment]
:sparkles::+1::sparkles: this talk must be excited!! :heart::heart::heart:

to organizers:
I believe his talk will be better than mine submitted.However, he will give his talk in English (yes, I'll give my talk in Japanese) and my talk will be brief introduction of DCI. Of course I can arrange my talk avoid conflict in the topic(if my talk will be accepted), but I think you guys should
select his talk if the reject reason is only because he was late for submitting proposal the deadline on JST

**Comment by apotonick** [comment]
@kakutani Your talk looks amazing! DCI is just a small concept in my talk and I don't think we would interfere at all since I focus more on gems and other OOP concepts, so go for it!

**Comment by hsbt** [comment]
+1

**Comment by adzuki34** [comment]
:thumbsup:

**Comment by noplans** [comment]
:+1:

**Comment by agrimm** [comment]
:+1:

**Comment by moro** [comment]
:+1

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Pull request merged**
