### PR TITLE
Millions of Apps Deployed: What We've Learned

### PR DESCRIPTION
**Pull request by schneems**
Heroku has deployed over a million web apps. When you've run that many applications, it's hard not to notice when frameworks and developers do things wrong, and when they do them right. We've taken a look at the most common patterns and boiled down the best of our advice in to 12 simple factors that can help you build your next app to be stable, successful, and scaleable. After this talk you'll walk away with in depth knowledge of web framework design patterns and practical examples of how to improve your application code. 
## Richard Schneeman

Richard comes from Austin, Tx with an appetite for Tacos and writing Gems. He's working with Heroku where he gets paid to play with his favorite toys. When he's not at work, he teaches Rails classes at the University of Texas, volunteers for the Rails Hotline and plays german board games.

Profile picture
- [My website](http://schneems.com)
- [My twitter](https://twitter.com/#!/schneems)
- [Past talk slides on Slideshare](http://www.slideshare.net/thinkbohemian)
- [Scaling the Web:databases & NoSQL](http://www.youtube.com/watch?v=oL-A4JYwgH4&feature=plcp&context=C4f2e5c6VDvjVQa1PpcFMqe8uD1JU48TxZwNUrEFIdD3DieAPMtPQ%3D)

### CODE REVIEW

**Comment by sorah** [comment]
:thumbsup:

**Comment by yuki24** [comment]
:+1:

**Comment by knsmr** [comment]
:+1:

**Comment by kakutani** [comment]
:+1:

**Comment by moro** [comment]
:+1:

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

We are sorry to inform you that we could not allocate time for your presentation in the plenary session.
We are also planning to have lightning talk sessions.
If you are intrested, please submit a lightning talk.
Furthermore, there will be a parallel "Unconference" and you may have opportunity to present there.

### About ticket reservation

All proposal submitters are welcome to participate in SPRK2012. We would like to offer you one free ticket to the plenary session.

If you would like to attend, please send the following information to sapporo2012@rubykaigi.org no later than Wednesday, June 7, 2012.
- Subject: sprk2012 ticket application
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 に応募いただきましたこの発表ですが、
大変残念ですが採択に至りませんでした。

LT を合計11枠用意する予定ですので、
ぜひ LT での応募をご検討頂ければと思います。
また会期中にアンカンファレンスも並行で実施する予定ですので
こちらへの参加も併せてご検討ください。

### チケットの取り置きについて

今回発表のお申し込みをいただいた方には、是非とも
Sapporo RubyKaigi2012 に参加してほしいと考えています。

6/7までに以下のフォーマットで申し込みをいただければ
本編チケットを無料で提供するようにいたします。
是非ともご検討下さい。
- Subject: sprk2012 ticket application
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Pull request closed without merging**
