### PR TITLE
Programming Workout talk by Michał Taszycki

### PR DESCRIPTION
**Pull request by mehowte**

### CODE REVIEW

**Comment by felipeelias** [comment]
:+1: definitely

**Comment by rodzyn** [comment]
+1

**Comment by piotrm** [comment]
Great topic, fantastic speaker. +1!

**Comment by nbartlomiej** [comment]
:+1: !

**Comment by domininik** [comment]
I saw him at Railsberry. Very good speaker!

**Comment by henieek** [comment]
+1

**Comment by kakutani** [comment]
hits talk looks interesting to me. :+1:

**Comment by nazgob** [comment]
+1, very cool stuff

**Comment by andrzejkrzywda** [comment]
+1

I've seen this talk twice, at wroc_love.rb and at RailsBerry, both awesome! 

Would love to see it again, very motivating.

**Comment by wsoczynski** [comment]
+1

**Comment by kiszal** [comment]
+!

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Pull request merged**
