### PR TITLE
Andrew Grimm: Japanese - a programmer's language

### PR DESCRIPTION
**Pull request by agrimm**
At first glance, Japanese looks to westerners like a very strange and difficult language. However, in many ways it is more similar to English than other European languages are, and an increasing amount of its vocabulary comes from English. In addition, so far I have found Japanese to be a very logical language.

While half an hour is not sufficient to teach the entirety of the Japanese language, I intend to show a glimpse of what Japanese is like, and some of its interesting idiosyncrasies. This will include "English made in Japan" (wasei-eigo), honorifics such as the "san" in "Daniel-san", and why both toilets and temples get the same "o" prefix (bikago).

### CODE REVIEW

**Comment by linyows** [comment]
:+1:

**Comment by darashi** [comment]
:+1:

**Comment by mrkn** [comment]
:thumbsup:

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Pull request merged**
