### PR TITLE
add my CFP for sapporo rubykaigi 2012

### PR DESCRIPTION
**Pull request by yokolet**
Let me send my pull request for sapporo rubykaigi 2012 CFP.
Looking forward to hearing a good one from you.

### CODE REVIEW

**Comment by amatsuda** [comment]
:gem::trophy::exclamation:
:us::rocket::octocat::metal::sparkles:

**Comment by hsbt** [comment]
:+1:

**Comment by agrimm** [comment]
:+1:

**Comment by hone** [comment]
:+1: this sounds like a great talk. There's a lot of cross-pollination that can happen between Japanese and US ruby developers.

**Comment by pwim** [comment]
:+1: :+1: This is a very important talk. I first found out about @yokolet when I was looking through the schedule of RubyConf 2010, and she was one of only three Japanese presenters. We need more Japanese rubyists to go abroad so that the Japanese ruby community becomes less isolated.

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Comment by hone** [comment]
@yokolet congrats!

**Comment by yokolet** [comment]
@hone thanks!

It's so nice! I'm totally happy with that.

**Pull request merged**
