### PR TITLE
Add my proposal: Inside 30days Album - Fighting against legacy Rails

### PR DESCRIPTION
**Pull request by kyanny**
In my presentation, I'll talk about the knowledge, difficulty and attitude of fighting legacy Rails application.

### CODE REVIEW

**Comment by mizzy** [comment]
:+1:

**Comment by linyows** [comment]
:metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal:

**Comment by agrimm** [comment]
:+1: I need to know how to manage legacy code - code that's been written by past-self!

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Comment by kyanny** [comment]
@snoozer05 Thank you for acceptance of my proposal. I sent email.

**Pull request merged**
