### PR TITLE
moro: Let your test drive your development

### PR DESCRIPTION
**Pull request by moro**
I'll talk about "thought" during writing developper tests by RSpec, Cucumber or so 
as I would like audiences to let thier tests drives their software development.

### CODE REVIEW

**Comment by koic** [comment]
s/developper/developer/

**Comment by moro** [comment]
@koic @agrimm thank you for reviews!!

**Comment by koic** [comment]
I'll be looking forward to your presentation :-)

**Comment by kakutani** [comment]
:+1:

**Comment by agrimm** [comment]
:+1:

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Pull request merged**
