### PR TITLE
Scaling in the unknown, how GitHub develops, ships and supports GitHub Enterprise.

### PR DESCRIPTION
**Pull request by calavera**
Everybody talks about scaling up, but, what happens when you have to scale down? or even, what happens when you don't control where your product is being deployed? In this session we'll talk about how we build GitHub enterprise, keeping every feature that you can find in github.com, and how we ship it ready to deploy on your infrastructure.

### CODE REVIEW

**Comment by takai** [comment]
:+1:

**Comment by hsbt** [comment]
:+1:

**Comment by sorah** [comment]
:thumbsup:

**Comment by kakutani** [comment]
:+1:

**Comment by linyows** [comment]
:metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal::metal:

**Comment by yuki24** [comment]
:+1:

**Comment by tricknotes** [comment]
:+1:

**Comment by darashi** [comment]
:+1:

**Comment by snoozer05** [comment]
## English

Thank you for your proposal for Sapporo RubyKaigi2012.

Congratulations! We’re pleased to tell you that your proposal was accepted.

Please join the speaker mailing-list so that we can adjust the
timetable for your presentation. Please send an e-mail to
sapporo2012@rubykaigi.org by June 7 with the following format:
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: the URL of your pull request

## Japanese

この度はご応募いただきありがとうございました。

Sapporo RubyKaigi2012 発表に採択されたことをお知らせします。おめでとうございます。

タイムテーブルの調整などを行う必要がありスピーカー向けのメーリングリストに入っていただきたいので、
6/7 までに以下のフォーマットで sapporo2012@rubykaigi.org までメールにてご連絡ください。
- Subject: sprk2012 speaker
- To: sapporo2012@rubykaigi.org
- Body: pull requestのURL

**Comment by snoozer05** [comment]
As I asked in the message above, we need your mail address to add for the speaker mailing-list.
Could I just add the address on your github?

**Pull request merged**
